if(PROFILE AND PROFILE_LIB)
    set(OPTS_APP_LIBS ${OPTS_APP_LIBS} ${PROFILE_LIB})
    set(OPTS_TEST_LIBS ${OPTS_TEST_LIBS} ${PROFILE_LIB})
endif()

if(SANITIZER AND SANITIZER_LIBS)
    set(OPTS_APP_LIBS ${OPTS_APP_LIBS} ${SANITIZER_LIBS})
    set(OPTS_TEST_LIBS ${OPTS_TEST_LIBS} ${SANITIZER_LIBS})
endif()
