set(PROJECT {{PROJECT}})
set(VERSION {{VERSION}})
set(PROJECT_COMPILE_FEATURES{%if {{ CXX }} %} cxx_std_{{ CXX_STD }}{%endif%}{%if {{ C_STD }} %} c_std_{{ C_STD }}{%endif%})

if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(_CI_MODE ON)
    if(DEFINED ENV{DEVENV})
        set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
    endif()
else()
    set(_CI_MODE OFF)
endif()
