if(LINK_STDLIB)
    if(NOT LINK_STDLIB IN_LIST STDLIBS_LIST)
        message(STATUS "LINK_STDLIB options can be set to: ${STDLIBS}")
        message(FATAL_ERROR "Can't link with: ${LINK_STDLIB}")
    endif()
    add_link_options(-stdlib=${LINK_STDLIB})
endif()
