macro (setup_package_version_variables)
    if (NOT DEFINED VERSION)
        set (VERSION "0.1.0")
    endif()

    string (REGEX MATCHALL "[0-9]+" _versionComponents "${VERSION}")
    list (LENGTH _versionComponents _len)
    if (${_len} GREATER 0)
        list(GET _versionComponents 0 VERSION_MAJOR)
    endif()
    if (${_len} GREATER 1)
        list(GET _versionComponents 1 VERSION_MINOR)
    endif()
    if (${_len} GREATER 2)
        list(GET _versionComponents 2 VERSION_PATCH)
    endif()
    if (${_len} GREATER 3)
        list(GET _versionComponents 3 VERSION_TWEAK)
    endif()
    set (VERSION_COUNT ${_len})
    set (VERSION_LIB "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
endmacro()

setup_package_version_variables()
